-- Pull in the wezterm API
local wezterm = require 'wezterm'
local config = wezterm.config_builder()

config.font_size = 16
config.window_background_opacity = 0.9
config.window_decorations = 'RESIZE'

-- bar.wezterm REPLACES config.colors wholesale (see its init.lua:74,
-- `c.colors = utilities._merge(default_colors, scheme)`), so it must be
-- applied BEFORE the palette or it silently discards it.
local bar = wezterm.plugin.require("https://github.com/adriankarlen/bar.wezterm")
bar.apply_to_config(config)

-- Theme: generated by bin/theme.py. Applied AFTER the bar plugin because
-- bar.wezterm REPLACES config.colors wholesale (its init.lua:74).
local ok, theme = pcall(dofile, os.getenv("HOME") .. "/.config/wezterm-theme.lua")
if ok and type(theme) == "table" then
  config.colors = config.colors or {}
  for k, v in pairs(theme) do config.colors[k] = v end
end

return config
